gtfsbeat:
  period: 1m
  url:    "http://gtfs.viainfo.net/gtfs-realtime/trapezerealtimefeed.pb",
processors:
- add_cloud_metadata: ~

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
  username: '${ELASTICSEARCH_USERNAME:}'
  password: '${ELASTICSEARCH_PASSWORD:}'
